#=========================================================================
# Mentor Calibre DRC
#=========================================================================
# Author : Christopher Torng
# Date   : November 5, 2019
#

name: mentor-calibre-drc

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - design_merged.gds
  - adk

outputs:
  - drc.results
  - drc.summary
  - drc.log

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------


commands:
  - mkdir -p logs
  - mkdir -p reports
  - envsubst < drc.runset.template > drc.runset
  - calibre -gui -drc -batch -runset drc.runset

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

#-------------------------------------------------------------------------
# Debug
#-------------------------------------------------------------------------

debug:
  - calibredrv -m inputs/design_merged.gds \
               -l inputs/adk/calibre.layerprops \
               -rve -drc drc.results

