#=========================================================================
# Cadence Innovus
#=========================================================================
# Author : Christopher Torng
# Date   : October 30, 2019
#

name: cadence-innovus-place

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - innovus-foundation-flow
  - innovus-plugins
  - adk
  - design.sdc
  - design.enc.dat
  - design.enc

outputs:
  - design.enc.dat
  - design.enc

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - ln -sf inputs/innovus-foundation-flow
  - innovus -overwrite -64 -nowin
    -init innovus-foundation-flow/INNOVUS/run_place.tcl
    -log run.log

  # Outputs
  - cd outputs
  - ln -sf ../checkpoints/design.enc.dat
  - ln -sf ../checkpoints/design.enc

#-------------------------------------------------------------------------
# Debug
#-------------------------------------------------------------------------

debug:
  - innovus -overwrite -64 -init run_debug.tcl -log debug.log

