#=========================================================================
# Cadence Innovus Power Includes for Sky130
#=========================================================================
# Author : James Thomas
# Date   : Feb 9, 2021
#

name: cadence-innovus-power-includes-sky130

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - main.tcl
  - power-strategy-singlemesh.tcl
  - globalnetconnect.tcl

