#=========================================================================
# Synopsys DC Synthesis
#=========================================================================
# Author : Christopher Torng
# Date   : January 22, 2020
#

name: synopsys-dc-synthesis-simple

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - adk
  - design.v

outputs:
  - design.v
  - design.sdc

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - dc_shell-xg-t -f dc.tcl

  # Outputs
  - mkdir -p outputs && cd outputs
  - ln -sf ../post-synth.v   design.v
  - ln -sf ../post-synth.sdc design.sdc

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  clock_period: 1.0
  design_name: undefined

