#=========================================================================
# Mentor Calibre GDS Merge
#=========================================================================
# Author : Christopher Torng
# Date   : November 5, 2019
#

name: mentor-calibre-gdsmerge

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - design.gds.gz
  - adk

outputs:
  - design_merged.gds

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------


commands:
  - set -x
  # For some reason, Calibre requires this directory to exist
  - mkdir -p $HOME/.calibrewb_workspace/tmp
  - calibredrv -a layout filemerge \
               -indir inputs \
               -in inputs/adk/stdcells.gds \
               -topcell {design_name} \
               -out design_merged.gds > merge.log 2>&1
  - mkdir -p outputs && cd outputs
  - ln -sf ../design_merged.gds

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

#-------------------------------------------------------------------------
# Debug
#-------------------------------------------------------------------------

debug:
  - calibredrv -m design_merged.gds \
               -l inputs/adk/calibre.layerprops

