#=========================================================================
# Synopsys PT Timing Signoff
#=========================================================================
# Author : Alex Carsello
# Date   : January 31, 2020
#

name: synopsys-pt-timing-signoff

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

# We will also get SPEF files for any blocks in the design.
# These will be added as inputs in construct.py.
inputs:
  - adk
  - design.v
  - design.sdc
  - design.spef

outputs:
  - design.sdf

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - bash run.sh

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

