#=========================================================================
# Synopsys VCS -- Generic VCS Simulation
#=========================================================================

name: synopsys-vcs-sim

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - adk
  - design.vcs.v
  - testbench.sv
  - design.sdf
  - design.args

outputs:
  - design.vpd

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - ./run.sh

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  clock_period: 1.0
  testbench_name: tb
