#=========================================================================
# Cadence Innovus
#=========================================================================
# Author : Christopher Torng
# Date   : November 8, 2019
#

name: cadence-innovus-debug-calibre

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - innovus-foundation-flow
  - innovus-plugins
  - adk
  - design.enc.dat
  - design.enc
  - drc.results
  - lvs.results

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  # Set up innovus debug view
  - ln -sf inputs/innovus-foundation-flow
  - mkdir -p checkpoints
  - cd checkpoints && ln -sf ../inputs/design.enc* . && cd ..
  # Open innovus debug view
  - innovus -overwrite -64 -init run_debug.tcl -log debug.log


