#=========================================================================
# sandwich
#=========================================================================

name: sandwich

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - half_1.txt
  - half_2.txt

outputs:
  - ~: sandwich.txt

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - make sandwich

