#=========================================================================
# jelly
#=========================================================================

name: jelly

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - slice_of_bread.txt

outputs:
  - jelly_on_bread.txt: results/out.txt

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - make

