#=========================================================================
# VCD to SAIF
#=========================================================================
# Author : Yanghui Ou
#   Date : Aug 15, 2019
#

name: vcd-to-saif

inputs:
  - run.vcd

outputs:
  - run.saif

commands:
  - vcd2saif -input inputs/run.vcd -output outputs/run.saif
