#=========================================================================
# Mentor Calibre LVS
#=========================================================================
# Author : Christopher Torng
# Date   : November 5, 2019
#

name: mentor-calibre-lvs

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - rules.svrf
  - design_merged.gds
  - design.lvs.v
  - adk

outputs:
  - lvs.report
  - design.schematic.spi

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - envsubst < lvs.runset.template > lvs.runset
  - if [ ! -f inputs/*.svrf ]; then touch inputs/rules.svrf; fi
  - calibre -gui -lvs -batch -runset lvs.runset
  - mkdir -p outputs && cd outputs
  - ln -sf ../lvs.report
  - ln -sf ../_design.lvs.v.sp design.schematic.spi

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

#-------------------------------------------------------------------------
# Debug
#-------------------------------------------------------------------------

debug:
  - calibredrv -m inputs/design_merged.gds \
               -l inputs/adk/calibre.layerprops \
               -rve -lvs svdb

