#=========================================================================
# bread
#=========================================================================

name: bread

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:

outputs:
  - slice1.txt
  - slice2.txt

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - mkdir -p outputs
  - echo '============== <-- bread' > outputs/slice1.txt
  - echo '============== <-- bread' > outputs/slice2.txt

