#=========================================================================
# Cadence Innovus
#=========================================================================
# Author : Christopher Torng
# Date   : October 30, 2019
#

name: cadence-innovus-postcts_hold

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - innovus-foundation-flow
  - innovus-plugins
  - adk
  - design.sdc
  - cts.enc.dat
  - cts.enc

outputs:
  - postcts_hold.enc.dat
  - postcts_hold.enc

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - ln -sf inputs/innovus-foundation-flow
  - mkdir -p checkpoints
  - cd checkpoints && ln -sf ../inputs/cts.enc* . && cd ..
  - innovus -overwrite -64 -nowin
    -init innovus-foundation-flow/INNOVUS/run_postcts_hold.tcl
    -log run.log

  # Outputs
  - cd outputs
  - ln -sf ../checkpoints/postcts_hold.enc.dat
  - ln -sf ../checkpoints/postcts_hold.enc

#-------------------------------------------------------------------------
# Debug
#-------------------------------------------------------------------------

debug:
  - export STEP=postcts_hold
  - innovus -overwrite -64
    -init innovus-foundation-flow/INNOVUS/run_debug.tcl
    -log debug.log

