#=========================================================================
# peanut_butter
#=========================================================================

name: peanut_butter

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - slice_of_bread.txt

outputs:
  - peanut_butter_on_bread.txt

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - make

