#=========================================================================
# Cadence Innovus Plugins
#=========================================================================
# Author : Christopher Torng
# Date   : June 7, 2019
#

name: cadence-innovus-plugins

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - innovus-plugins

